spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}
  port: ${SERVER_PORT}